[[project]]
name = "Save Yourself"
desc = "Save Yourself is a 2D atmospheric puzzle-platformer where you place save points to undo mistakes. With a calm, bittersweet soundtrack and an atmosphere of cold colors, it creates a world that feels safe—maybe too safe. Made by myself for a one week long Game Jam,  the original music, the visual design and the code were all crafted from scratch. Built around the theme \"Nothing Can Go Wrong\", the game challenges you to think ahead and question the comfort of a world where mistakes don’t matter."
tags = ["puzzlegame", "platformer", "gamejam"]
links = [
    { name = "itchio", url = "https://marcusjensen.itch.io/save-yourself" },
    { name = "article", url = "https://kirbylife.co.uk/2025/04/14/case-study-my-playtest-process-for-save-yourself-puzzle-platformer/" },
]

[[project]]
name = "Uncanny"
desc = "Uncanny is an action game where the player must survive by dodging and dashing through uncanny boss attacks. The game is set in a funny and uncanny atmosphere, where the player can play with the music. As the game progresses, the monsters become more challenging to dodge, and the player must use quick reflexes and timing to survive."
tags = ["bullethell", "rhythm", "gamedev"]
links = [
    { name = "itchio", url = "https://marcusjensen.itch.io/uncanny" },
    { name = "github", url = "https://github.com/marcusaasjensen/uncanny-game-project" },
]
