[[experience]]
name = "Cloud UI Engineer Intern"
desc = "Collaborated with a team of four engineers to build a JavaScript library in SAPUI5, enabling Joule AI (LLM) to convert user prompts into metric visualizations (graphs, tables, charts) for automated dashboard generation in SAP Cloud ALM solution."
start_date = "Mar 2025"
end_date = "Aug 2025"
location = "SAP Labs, France"
logo = "/images/sap.png"
links = [{ name = "SAP Labs France", url = "https://www.sap.com" }]

[[experience]]
name = "Frontend Engineer Intern"
desc = "Architected a customizable operations monitoring dashboard using Angular, AmCharts 5, and GridstackJS, centralizing transaction, error, and response-time monitoring with 10 key visualizations."
start_date = "May 2024"
end_date = "Aug 2024"
location = "Amadeus, France"
logo = "/images/amadeus.png"
links = [{ name = "Amadeus", url = "https://amadeus.com" }]

[[experience]]
name = "Mobile Developer Intern"
desc = "Implemented the frontend of an emergency messaging mobile app with React Native (JavaScript) for iOS and Android in a team of four students."
start_date = "May 2022"
end_date = "Jul 2022"
location = "DNIIT, Vietnam"
logo = "/images/dniit.png"
links = [
    { name = "Da Nang International Institute of Technology", url = "https://www.udn.vn/" },
]

[[education]]
name = "Computer Science Engineering Degree"
desc = "Specialization in software engineering and user interactions."
start_date = "Sep 2022"
end_date = "Sep 2025"
location = "Polytech Nice Sophia, France"
logo = "/images/polytech.png"
links = [
    { name = "Polytech Nice Sophia", url = "https://www.polytech.unice.fr/" },
]

[[education]]
name = "Semester Abroad in Canada 🍁"
desc = "Courses in game development, Unreal Engine, C++ and mathematics."
start_date = "Jan 2022"
end_date = "Apr 2022"
location = "UQAC, Canada"
logo = "/images/uqac.png"
links = [
    { name = "Université du Québec à Chicoutimi", url = "https://www.uqac.ca/" },
]

[[education]]
name = "Associate Degree in Computer Science"
desc = "Fundamentals of computer science, programming, algorithms and web development."
start_date = "Sep 2020"
end_date = "Jul 2022"
location = "IUT Nice Côte d'Azur, France"
logo = "/images/iut.png"
links = [
    { name = "IUT Nice Côte d'Azur", url = "https://iut.univ-cotedazur.fr/" },
]

[[skills]]
title = "Programming Languages"
items = [
    { name = "C#", url = "https://en.wikipedia.org/wiki/C_Sharp_(programming_language)" },
    { name = "C++", url = "https://en.wikipedia.org/wiki/C%2B%2B" },
    { name = "Java", url = "https://en.wikipedia.org/wiki/Java_(programming_language)" },
    { name = "JavaScript", url = "https://en.wikipedia.org/wiki/JavaScript" },
    { name = "TypeScript", url = "https://en.wikipedia.org/wiki/TypeScript" },
    { name = "HTML", url = "https://en.wikipedia.org/wiki/HTML" },
    { name = "CSS", url = "https://en.wikipedia.org/wiki/CSS" },
]

[[skills]]
title = "3D Tools & Techniques"
items = [
    { name = "Unity 3D", url = "https://en.wikipedia.org/wiki/Unity_(game_engine)" },
    { name = "Blender", url = "https://en.wikipedia.org/wiki/Blender_(software)" },
    { name = "Scriptable Objects", url = "https://docs.unity3d.com/Manual/class-ScriptableObject.html" },
    { name = "3D Rendering", url = "https://en.wikipedia.org/wiki/3D_computer_graphics#Rendering" },
    { name = "Rasterization", url = "https://en.wikipedia.org/wiki/Rasterisation" },
]

[[skills]]
title = "User Experience"
items = [
    { name = "Frontend", url = "https://en.wikipedia.org/wiki/Frontend_development" },
    { name = "UI", url = "https://en.wikipedia.org/wiki/User_interface" },
    { name = "UX", url = "https://en.wikipedia.org/wiki/User_experience" },
    { name = "Figma", url = "https://en.wikipedia.org/wiki/Figma_(software)" },
    { name = "Scenarios", url = "https://en.wikipedia.org/wiki/Use_case" },
    { name = "Accessibility", url = "https://en.wikipedia.org/wiki/Accessibility" },
    { name = "Game Feel", url = "https://en.wikipedia.org/wiki/Game_feel" },
    { name = "VR", url = "https://en.wikipedia.org/wiki/Virtual_reality" },
    { name = "AR", url = "https://en.wikipedia.org/wiki/Augmented_reality" },
    { name = "XR", url = "https://en.wikipedia.org/wiki/Extended_reality" },
    { name = "HoloLens", url = "https://en.wikipedia.org/wiki/Microsoft_HoloLens" },
    { name = "Meta Quest", url = "https://en.wikipedia.org/wiki/Meta_Quest" },
    { name = "Multimodality interaction", url = "https://en.wikipedia.org/wiki/Multimodal_interaction" },
]

[[skills]]
title = "Software Architecture & Engineering"
items = [
    { name = "OOP", url = "https://en.wikipedia.org/wiki/Object-oriented_programming" },
    { name = "Design Patterns", url = "https://en.wikipedia.org/wiki/Software_design_pattern" },
    { name = "UML", url = "https://en.wikipedia.org/wiki/Unified_Modeling_Language" },
    { name = "Qt", url = "https://en.wikipedia.org/wiki/Qt_(software)" },
    { name = "Angular", url = "https://en.wikipedia.org/wiki/Angular_(application_platform)" },
    { name = "React Native", url = "https://en.wikipedia.org/wiki/React_Native" },
    { name = "REST APIs", url = "https://en.wikipedia.org/wiki/Representational_state_transfer" },
    { name = "Git", url = "https://en.wikipedia.org/wiki/Git" },
    { name = "GitHub", url = "https://en.wikipedia.org/wiki/GitHub" },
    { name = "Jira", url = "https://en.wikipedia.org/wiki/Jira_(software)" },
    { name = "Confluence", url = "https://en.wikipedia.org/wiki/Confluence_(software)" },
    { name = "Agile", url = "https://en.wikipedia.org/wiki/Agile_software_development" },
]

[[certifications]]
name = "TOEIC"
desc = "Scored 905/990"
date = "Jan 2023"
links = [{ name = "ETS Global", url = "https://www.etsglobal.org/" }]

[[certifications]]
name = "French Driving License"
date = "Jul 2022"
links = [{ name = "Service-Public.fr", url = "https://www.service-public.fr/" }]

[[certifications]]
name = "Youth Worker Diploma"
desc = "Training from Ceméa organization with experience in leading and supervising children and teenagers during leisure activities."
date = "Fev 2020"
links = [
    { name = "Ceméa", url = "https://cemea.asso.fr/qui-sommes-nous/une-structure-associative" },
]

[[Languages]]
name = "French"
level = "Native"
flag = "/images/france.png"

[[Languages]]
name = "English"
level = "Fluent"
flag = "/images/uk.png"

[[Languages]]
name = "Japanese"
level = "Basic"
flag = "/images/japan.png"
